--ROLLUP
SELECT country, year, SUM(amount) as totalsales
FROM SOFTCARTFACTSALES
LEFT JOIN SOFTCARTDIMCOUNTRY
ON SOFTCARTFACTSALES.countryid = SOFTCARTDIMCOUNTRY.countryid
LEFT JOIN SOFTCARTDIMDATE
ON SOFTCARTFACTSALES.dateid = SOFTCARTDIMDATE.dateit
GROUP BY ROLLUP(country, year)
ORDER BY country, year;

--CUBE
SELECT country, year, SUM(amount) as totalsales
FROM SOFTCARTFACTSALES
LEFT JOIN SOFTCARTDIMCOUNTRY
ON SOFTCARTFACTSALES.countryid = SOFTCARTDIMCOUNTRY.countryid
LEFT JOIN SOFTCARTDIMDATE
ON SOFTCARTFACTSALES.dateid = SOFTCARTDIMDATE.dateit
GROUP BY CUBE(country, year)
ORDER BY country, year;

--GROUPING SETS
SELECT country, year, SUM(amount) as totalsales
FROM SOFTCARTFACTSALES
LEFT JOIN SOFTCARTDIMCOUNTRY
ON SOFTCARTFACTSALES.countryid = SOFTCARTDIMCOUNTRY.countryid
LEFT JOIN SOFTCARTDIMDATE
ON SOFTCARTFACTSALES.dateid = SOFTCARTDIMDATE.dateit
GROUP BY GROUPING SETS(country, year)
ORDER BY country, year;

--MQT
CREATE TABLE total_sales_per_country (country, total_sales) AS
(   
    SELECT country, sum(amount)
    FROM SOFTCARTFACTSALES
    LEFT JOIN SOFTCARTDIMCOUNTRY
    ON SOFTCARTFACTSALES.countryid = SOFTCARTDIMCOUNTRY.countryid
    GROUP BY country
)
    DATA INITIALLY DEFERRED
    REFRESH DEFERRED
    MAINTAINED BY SYSTEM;
